import type { Language } from "./rediscover-languages";

type FeatureCopy = {
  opmlDetail: string;
  sharedDetail: string;
  jevDetail: string;
  routerDetail: string;
  featuresNav: string;
  featuresTitle: string;
  opmlTitle: string;
  opmlBody: string;
  sharedTitle: string;
  sharedBody: string;
  jevTitle: string;
  jevBody: string;
  routerTitle: string;
  routerBody: string;
  plansNav: string;
  plansTitle: string;
  plansIntro: string;
  freeName: string;
  freeBilling: string;
  proName: string;
  proBilling: string;
  plusName: string;
  plusBilling: string;
  freeLimits: string;
  freeShared: string;
  cloudFree: string;
  unlimited: string;
  imports: string;
  sync: string;
  byok: string;
  proShared: string;
  allPro: string;
  cloudPlus: string;
  plusShared: string;
  pricingNote: string;
  cta: string;
};

export const featureTranslations = {
  "en": {
    "featuresNav": "Features",
    "featuresTitle": "More ways to follow your curiosity.",
    "opmlTitle": "Bring your subscriptions along.",
    "opmlBody": "Import an OPML subscription file into Radar with Pro or Pro+ and keep your favorite sources together.",
    "sharedTitle": "Shared, for reading together.",
    "sharedBody": "Share pages in shared-reading spaces. Joining is free; your plan determines how many active spaces you can create.",
    "jevTitle": "Small decisions, with Jev.",
    "jevBody": "Turn on optional Jev Decisions in Cloud or BYOK mode to help with Radar timing and category organization.",
    "routerTitle": "Your models, through OpenRouter.",
    "routerBody": "Use your own OpenRouter API key with Pro or Pro+. Your key stays in Keychain; model usage is billed by your provider.",
    "plansNav": "Plans",
    "plansTitle": "A plan for the way you read.",
    "plansIntro": "Start free. Choose a one-time purchase or a subscription when you need more.",
    "freeName": "Free",
    "freeBilling": "Get to know Rediscover",
    "proName": "Pro",
    "proBilling": "One-time purchase · Lifetime",
    "plusName": "Pro+",
    "plusBilling": "Monthly or annual subscription",
    "freeLimits": "15 saved articles · 3 Radar sources",
    "freeShared": "Create 1 shared-reading space",
    "cloudFree": "Cloud Free",
    "unlimited": "Unlimited saved articles and Radar sources",
    "imports": "Saved-page and OPML imports",
    "sync": "iCloud sync across devices",
    "byok": "OpenRouter BYOK",
    "proShared": "Create 3 shared-reading spaces",
    "allPro": "Everything in Pro",
    "cloudPlus": "Cloud AI without your own API key, with higher usage limits",
    "plusShared": "Unlimited shared-reading spaces",
    "pricingNote": "See local prices and purchase options in the app. Cloud usage limits apply; BYOK model costs are separate.",
    "cta": "Explore Rediscover",
    "opmlDetail": "Move your feed subscriptions from another reader into Radar. OPML imports sources, so you can continue discovering their new writing.",
    "sharedDetail": "Create a space, invite others, and share pages worth discussing. Keep a shared reading collection alongside your personal Library.",
    "jevDetail": "Jev helps make focused decisions, such as when to surface Radar discoveries and how to organize categories. Enable it separately when you want this assistance.",
    "routerDetail": "Use cloud models for summaries, classification, and reading guides. BYOK gives you control over your OpenRouter connection; Pro+ also offers managed Cloud AI."
  },
  "zh-Hans": {
    "featuresNav": "新功能",
    "featuresTitle": "让好奇心，多几种去处。",
    "opmlTitle": "把订阅一起带过来。",
    "opmlBody": "使用 Pro 或 Pro+ 将 OPML 订阅文件导入 Radar，让喜欢的内容来源汇聚一处。",
    "sharedTitle": "Shared，一起读好内容。",
    "sharedBody": "在共读空间中分享网页。加入空间免费；可创建的活跃空间数量取决于你的方案。",
    "jevTitle": "让 Jev 帮忙做些小决定。",
    "jevBody": "在 Cloud 或 BYOK 模式下，可选择开启 Jev Decisions，辅助 Radar 时机判断和分类整理。",
    "routerTitle": "通过 OpenRouter，选择自己的模型。",
    "routerBody": "Pro 和 Pro+ 支持自带 OpenRouter API Key。密钥存放在系统钥匙串中，模型用量由服务商另行计费。",
    "plansNav": "方案",
    "plansTitle": "找到适合你的阅读方案。",
    "plansIntro": "从免费开始，需要更多时，选择终身买断或订阅。",
    "freeName": "免费版",
    "freeBilling": "从这里认识 Rediscover",
    "proName": "Pro",
    "proBilling": "一次购买 · 终身使用",
    "plusName": "Pro+",
    "plusBilling": "按月或按年订阅",
    "freeLimits": "保存 15 篇文章 · 3 个 Radar 来源",
    "freeShared": "创建 1 个共读空间",
    "cloudFree": "Cloud Free",
    "unlimited": "无限保存文章与 Radar 来源",
    "imports": "导入已存网页与 OPML 订阅",
    "sync": "跨设备 iCloud 同步",
    "byok": "自带 OpenRouter API Key",
    "proShared": "创建 3 个共读空间",
    "allPro": "包含 Pro 的全部功能",
    "cloudPlus": "无需自备 API Key 的云端 AI，享有更高用量额度",
    "plusShared": "创建不限数量的共读空间",
    "pricingNote": "当地价格与购买选项请查看 App。云端服务设有用量限制；自带 API Key 的模型费用另计。",
    "cta": "探索 Rediscover",
    "opmlDetail": "从其他阅读器导出 OPML，再导入 Radar，继续追踪熟悉的内容来源。导入的是订阅源，方便以后发现它们的新文章。",
    "sharedDetail": "创建空间、邀请伙伴，把值得讨论的网页分享给彼此。在自己的资料库之外，也有一个一起积累好内容的地方。",
    "jevDetail": "Jev 负责更具体的判断，例如何时呈现 Radar 发现、如何整理分类。需要这类辅助时，可以单独开启。",
    "routerDetail": "使用云端模型生成摘要、分类和阅读指南。BYOK 让你自行管理 OpenRouter 连接；Pro+ 也提供无需自备密钥的 Cloud AI。"
  },
  "zh-Hant": {
    "featuresNav": "新功能",
    "featuresTitle": "讓好奇心，多幾種去處。",
    "opmlTitle": "把訂閱一起帶過來。",
    "opmlBody": "使用 Pro 或 Pro+ 將 OPML 訂閱檔案匯入 Radar，讓喜歡的內容來源匯聚一處。",
    "sharedTitle": "Shared，一起讀好內容。",
    "sharedBody": "在共讀空間中分享網頁。加入空間免費；可建立的活躍空間數量取決於你的方案。",
    "jevTitle": "讓 Jev 幫忙做些小決定。",
    "jevBody": "在 Cloud 或 BYOK 模式下，可選擇開啟 Jev Decisions，輔助 Radar 時機判斷和分類整理。",
    "routerTitle": "透過 OpenRouter，選擇自己的模型。",
    "routerBody": "Pro 和 Pro+ 支援自備 OpenRouter API Key。金鑰存放在系統鑰匙圈中，模型用量由服務商另行計費。",
    "plansNav": "方案",
    "plansTitle": "找到適合你的閱讀方案。",
    "plansIntro": "從免費開始，需要更多時，選擇終身買斷或訂閱。",
    "freeName": "免費版",
    "freeBilling": "從這裡認識 Rediscover",
    "proName": "Pro",
    "proBilling": "一次購買 · 終身使用",
    "plusName": "Pro+",
    "plusBilling": "按月或按年訂閱",
    "freeLimits": "儲存 15 篇文章 · 3 個 Radar 來源",
    "freeShared": "建立 1 個共讀空間",
    "cloudFree": "Cloud Free",
    "unlimited": "無限儲存文章與 Radar 來源",
    "imports": "匯入已存網頁與 OPML 訂閱",
    "sync": "跨裝置 iCloud 同步",
    "byok": "自備 OpenRouter API Key",
    "proShared": "建立 3 個共讀空間",
    "allPro": "包含 Pro 的全部功能",
    "cloudPlus": "無需自備 API Key 的雲端 AI，享有更高用量額度",
    "plusShared": "建立不限數量的共讀空間",
    "pricingNote": "當地價格與購買選項請查看 App。雲端服務設有用量限制；自備 API Key 的模型費用另計。",
    "cta": "探索 Rediscover",
    "opmlDetail": "從其他閱讀器匯出 OPML，再匯入 Radar，繼續追蹤熟悉的內容來源。匯入的是訂閱來源，方便日後發現它們的新文章。",
    "sharedDetail": "建立空間、邀請夥伴，把值得討論的網頁分享給彼此。在自己的資料庫之外，也有一個一起累積好內容的地方。",
    "jevDetail": "Jev 負責更具體的判斷，例如何時呈現 Radar 發現、如何整理分類。需要這類輔助時，可以單獨開啟。",
    "routerDetail": "使用雲端模型產生摘要、分類和閱讀指南。BYOK 讓你自行管理 OpenRouter 連線；Pro+ 也提供無需自備金鑰的 Cloud AI。"
  },
  "ja": {
    "featuresNav": "新機能",
    "featuresTitle": "好奇心の、その先へ。",
    "opmlTitle": "購読リストも一緒に。",
    "opmlBody": "Pro または Pro+ で OPML 購読ファイルを Radar に読み込み、お気に入りの情報源をまとめられます。",
    "sharedTitle": "Shared で、一緒に読む。",
    "sharedBody": "共同読書スペースでページを共有。参加は無料です。作成できる有効なスペースの数はプランによって異なります。",
    "jevTitle": "小さな判断を Jev に。",
    "jevBody": "Cloud または BYOK モードで任意の Jev Decisions を有効にすると、Radar のタイミング判断やカテゴリ整理を支援します。",
    "routerTitle": "OpenRouter で、自分のモデルを。",
    "routerBody": "Pro と Pro+ では自分の OpenRouter API キーを使えます。キーはキーチェーンに保存され、モデル利用料はプロバイダーから別途請求されます。",
    "plansNav": "プラン",
    "plansTitle": "読み方に合ったプランを。",
    "plansIntro": "無料で始めて、必要に応じて買い切りかサブスクリプションを選べます。",
    "freeName": "無料",
    "freeBilling": "Rediscover を試す",
    "proName": "Pro",
    "proBilling": "買い切り · 永続利用",
    "plusName": "Pro+",
    "plusBilling": "月額または年額",
    "freeLimits": "記事を15件保存 · Radar の情報源3件",
    "freeShared": "共同読書スペースを1つ作成",
    "cloudFree": "Cloud Free",
    "unlimited": "記事の保存・Radar の情報源が無制限",
    "imports": "保存済みページと OPML の読み込み",
    "sync": "デバイス間の iCloud 同期",
    "byok": "OpenRouter API キーの持ち込み",
    "proShared": "共同読書スペースを3つ作成",
    "allPro": "Pro の全機能",
    "cloudPlus": "自分の API キー不要のクラウド AI、より多い利用枠",
    "plusShared": "共同読書スペースを無制限に作成",
    "pricingNote": "地域の価格と購入方法はアプリで確認できます。クラウドには利用上限があります。BYOK のモデル利用料は別途必要です。",
    "cta": "Rediscover を見る",
    "opmlDetail": "別のリーダーから OPML を書き出して Radar に読み込めば、いつもの情報源を引き続き追えます。読み込むのは購読先なので、新しい記事の発見につながります。",
    "sharedDetail": "スペースを作成し、仲間を招待して、話し合いたいページを共有。自分のライブラリに加えて、みんなで読むコレクションを育てられます。",
    "jevDetail": "Radar の発見を提示するタイミングやカテゴリの整理など、具体的な判断を支援します。必要なときに個別に有効にできます。",
    "routerDetail": "クラウドモデルで要約、分類、読書ガイドを生成。BYOK なら OpenRouter 接続を自分で管理でき、Pro+ ならキー不要の Cloud AI も利用できます。"
  },
  "ko": {
    "featuresNav": "새로운 기능",
    "featuresTitle": "호기심을 이어 가는 더 많은 방법.",
    "opmlTitle": "구독 목록도 함께 가져오세요.",
    "opmlBody": "Pro 또는 Pro+에서 OPML 구독 파일을 Radar로 가져와 좋아하는 소스를 한곳에 모으세요.",
    "sharedTitle": "Shared로 함께 읽어요.",
    "sharedBody": "함께 읽는 공간에서 페이지를 공유하세요. 참여는 무료이며 만들 수 있는 활성 공간 수는 요금제에 따라 달라집니다.",
    "jevTitle": "작은 판단은 Jev와 함께.",
    "jevBody": "Cloud 또는 BYOK 모드에서 선택적으로 Jev Decisions를 켜면 Radar의 시점 판단과 카테고리 정리를 돕습니다.",
    "routerTitle": "OpenRouter로 나만의 모델을.",
    "routerBody": "Pro와 Pro+에서는 자신의 OpenRouter API 키를 사용할 수 있습니다. 키는 키체인에 저장되며 모델 사용료는 제공업체에서 별도로 청구합니다.",
    "plansNav": "요금제",
    "plansTitle": "읽는 방식에 맞는 요금제.",
    "plansIntro": "무료로 시작하고 더 필요할 때 평생 이용권이나 구독을 선택하세요.",
    "freeName": "무료",
    "freeBilling": "Rediscover 시작하기",
    "proName": "Pro",
    "proBilling": "한 번 구매 · 평생 이용",
    "plusName": "Pro+",
    "plusBilling": "월간 또는 연간 구독",
    "freeLimits": "기사 15개 저장 · Radar 소스 3개",
    "freeShared": "함께 읽는 공간 1개 만들기",
    "cloudFree": "Cloud Free",
    "unlimited": "기사 저장 및 Radar 소스 무제한",
    "imports": "저장된 페이지 및 OPML 가져오기",
    "sync": "기기 간 iCloud 동기화",
    "byok": "OpenRouter API 키 직접 사용",
    "proShared": "함께 읽는 공간 3개 만들기",
    "allPro": "Pro의 모든 기능",
    "cloudPlus": "개인 API 키 없이 쓰는 클라우드 AI, 더 높은 사용 한도",
    "plusShared": "함께 읽는 공간 무제한 생성",
    "pricingNote": "지역별 가격과 구매 옵션은 앱에서 확인하세요. 클라우드 사용 한도가 적용되며 BYOK 모델 비용은 별도입니다.",
    "cta": "Rediscover 살펴보기",
    "opmlDetail": "다른 리더에서 OPML을 내보내 Radar로 가져오면 익숙한 소스를 계속 구독할 수 있습니다. 구독 소스를 가져와 새 글을 발견하세요.",
    "sharedDetail": "공간을 만들고 친구를 초대해 함께 이야기할 페이지를 공유하세요. 개인 라이브러리와 함께 공동으로 읽을 모음도 쌓아 갈 수 있습니다.",
    "jevDetail": "Radar에서 발견한 글을 언제 보여줄지, 카테고리를 어떻게 정리할지 같은 구체적인 판단을 돕습니다. 필요할 때 별도로 켤 수 있습니다.",
    "routerDetail": "클라우드 모델로 요약, 분류, 읽기 가이드를 생성하세요. BYOK는 OpenRouter 연결을 직접 관리하며, Pro+는 개인 키가 필요 없는 Cloud AI도 제공합니다."
  },
  "fr": {
    "featuresNav": "Nouveautés",
    "featuresTitle": "D’autres chemins pour votre curiosité.",
    "opmlTitle": "Emportez vos abonnements.",
    "opmlBody": "Importez un fichier OPML dans Radar avec Pro ou Pro+ pour réunir vos sources favorites.",
    "sharedTitle": "Shared, pour lire ensemble.",
    "sharedBody": "Partagez des pages dans des espaces de lecture. Les rejoindre est gratuit ; votre formule détermine combien d’espaces actifs vous pouvez créer.",
    "jevTitle": "Les petites décisions, avec Jev.",
    "jevBody": "Activez Jev Decisions en mode Cloud ou BYOK pour aider à choisir le moment des découvertes Radar et à organiser les catégories.",
    "routerTitle": "Vos modèles, via OpenRouter.",
    "routerBody": "Utilisez votre clé API OpenRouter avec Pro ou Pro+. Elle reste dans le trousseau ; le fournisseur facture séparément l’utilisation des modèles.",
    "plansNav": "Formules",
    "plansTitle": "Une formule pour votre façon de lire.",
    "plansIntro": "Commencez gratuitement. Choisissez ensuite un achat unique ou un abonnement selon vos besoins.",
    "freeName": "Gratuit",
    "freeBilling": "Découvrez Rediscover",
    "proName": "Pro",
    "proBilling": "Achat unique · À vie",
    "plusName": "Pro+",
    "plusBilling": "Abonnement mensuel ou annuel",
    "freeLimits": "15 articles enregistrés · 3 sources Radar",
    "freeShared": "Créez 1 espace de lecture partagée",
    "cloudFree": "Cloud Free",
    "unlimited": "Articles enregistrés et sources Radar illimités",
    "imports": "Import de pages enregistrées et de fichiers OPML",
    "sync": "Synchronisation iCloud entre appareils",
    "byok": "Votre propre clé API OpenRouter",
    "proShared": "Créez 3 espaces de lecture partagée",
    "allPro": "Toutes les fonctionnalités Pro",
    "cloudPlus": "IA cloud sans clé API personnelle, avec des quotas plus élevés",
    "plusShared": "Espaces de lecture partagée illimités",
    "pricingNote": "Consultez les tarifs locaux et les options d’achat dans l’app. Des limites d’utilisation cloud s’appliquent ; les frais des modèles BYOK sont distincts.",
    "cta": "Explorer Rediscover",
    "opmlDetail": "Exportez vos abonnements au format OPML depuis un autre lecteur, puis importez-les dans Radar pour continuer à découvrir les nouveaux articles de vos sources habituelles.",
    "sharedDetail": "Créez un espace, invitez vos proches et partagez des pages qui méritent une discussion. Constituez une collection commune à côté de votre bibliothèque personnelle.",
    "jevDetail": "Jev aide à décider quand présenter les découvertes Radar et comment organiser les catégories. Activez cette aide séparément lorsque vous en avez besoin.",
    "routerDetail": "Utilisez des modèles cloud pour les résumés, le classement et les guides de lecture. BYOK vous laisse gérer votre connexion OpenRouter ; Pro+ propose aussi une IA cloud sans clé personnelle."
  },
  "de": {
    "featuresNav": "Neuigkeiten",
    "featuresTitle": "Mehr Wege für deine Neugier.",
    "opmlTitle": "Nimm deine Abonnements mit.",
    "opmlBody": "Importiere mit Pro oder Pro+ eine OPML-Datei in Radar und sammle deine Lieblingsquellen an einem Ort.",
    "sharedTitle": "Shared: gemeinsam lesen.",
    "sharedBody": "Teile Seiten in gemeinsamen Leseräumen. Der Beitritt ist kostenlos; dein Tarif bestimmt, wie viele aktive Räume du erstellen kannst.",
    "jevTitle": "Kleine Entscheidungen mit Jev.",
    "jevBody": "Aktiviere optional Jev Decisions im Cloud- oder BYOK-Modus, um Radar beim Timing und bei der Organisation von Kategorien zu unterstützen.",
    "routerTitle": "Deine Modelle über OpenRouter.",
    "routerBody": "Nutze mit Pro oder Pro+ deinen eigenen OpenRouter-API-Schlüssel. Er bleibt im Schlüsselbund; die Modellnutzung rechnet dein Anbieter separat ab.",
    "plansNav": "Tarife",
    "plansTitle": "Ein Tarif für deine Art zu lesen.",
    "plansIntro": "Starte kostenlos. Wähle bei Bedarf einen Einmalkauf oder ein Abonnement.",
    "freeName": "Kostenlos",
    "freeBilling": "Rediscover kennenlernen",
    "proName": "Pro",
    "proBilling": "Einmalkauf · Dauerhafter Zugang",
    "plusName": "Pro+",
    "plusBilling": "Monats- oder Jahresabo",
    "freeLimits": "15 gespeicherte Artikel · 3 Radar-Quellen",
    "freeShared": "1 gemeinsamen Leseraum erstellen",
    "cloudFree": "Cloud Free",
    "unlimited": "Unbegrenzte Artikel und Radar-Quellen",
    "imports": "Gespeicherte Seiten und OPML importieren",
    "sync": "iCloud-Synchronisierung zwischen Geräten",
    "byok": "Eigener OpenRouter-API-Schlüssel",
    "proShared": "3 gemeinsame Leseräume erstellen",
    "allPro": "Alle Pro-Funktionen",
    "cloudPlus": "Cloud-KI ohne eigenen API-Schlüssel, mit höheren Nutzungslimits",
    "plusShared": "Unbegrenzte gemeinsame Leseräume",
    "pricingNote": "Lokale Preise und Kaufoptionen findest du in der App. Für die Cloud gelten Nutzungslimits; BYOK-Modellkosten fallen separat an.",
    "cta": "Rediscover entdecken",
    "opmlDetail": "Exportiere deine Abonnements als OPML aus einem anderen Reader und importiere sie in Radar. So entdeckst du weiterhin neue Artikel deiner vertrauten Quellen.",
    "sharedDetail": "Erstelle einen Raum, lade andere ein und teile Seiten, über die ihr sprechen möchtet. So wächst neben deiner eigenen Bibliothek eine gemeinsame Lesesammlung.",
    "jevDetail": "Jev unterstützt konkrete Entscheidungen: wann Radar neue Entdeckungen zeigt und wie Kategorien organisiert werden. Du kannst diese Hilfe bei Bedarf separat einschalten.",
    "routerDetail": "Nutze Cloud-Modelle für Zusammenfassungen, Kategorien und Lesehilfen. Mit BYOK verwaltest du deine OpenRouter-Verbindung selbst; Pro+ bietet auch Cloud-KI ohne eigenen Schlüssel."
  },
  "es": {
    "featuresNav": "Novedades",
    "featuresTitle": "Más caminos para tu curiosidad.",
    "opmlTitle": "Lleva contigo tus suscripciones.",
    "opmlBody": "Importa un archivo OPML en Radar con Pro o Pro+ y reúne tus fuentes favoritas.",
    "sharedTitle": "Shared, para leer juntos.",
    "sharedBody": "Comparte páginas en espacios de lectura. Unirse es gratis; tu plan determina cuántos espacios activos puedes crear.",
    "jevTitle": "Pequeñas decisiones, con Jev.",
    "jevBody": "Activa opcionalmente Jev Decisions en modo Cloud o BYOK para ayudar con los momentos de descubrimiento en Radar y la organización de categorías.",
    "routerTitle": "Tus modelos, a través de OpenRouter.",
    "routerBody": "Usa tu propia clave API de OpenRouter con Pro o Pro+. Se guarda en el llavero; tu proveedor factura el uso de los modelos por separado.",
    "plansNav": "Planes",
    "plansTitle": "Un plan para tu forma de leer.",
    "plansIntro": "Empieza gratis. Elige una compra única o una suscripción cuando necesites más.",
    "freeName": "Gratis",
    "freeBilling": "Conoce Rediscover",
    "proName": "Pro",
    "proBilling": "Compra única · De por vida",
    "plusName": "Pro+",
    "plusBilling": "Suscripción mensual o anual",
    "freeLimits": "15 artículos guardados · 3 fuentes Radar",
    "freeShared": "Crea 1 espacio de lectura compartida",
    "cloudFree": "Cloud Free",
    "unlimited": "Artículos guardados y fuentes Radar ilimitados",
    "imports": "Importación de páginas guardadas y OPML",
    "sync": "Sincronización iCloud entre dispositivos",
    "byok": "Tu propia clave API de OpenRouter",
    "proShared": "Crea 3 espacios de lectura compartida",
    "allPro": "Todas las funciones de Pro",
    "cloudPlus": "IA en la nube sin clave API propia, con límites de uso más altos",
    "plusShared": "Espacios de lectura compartida ilimitados",
    "pricingNote": "Consulta los precios locales y las opciones de compra en la app. Se aplican límites de uso en la nube; los costes de modelos BYOK son independientes.",
    "cta": "Explorar Rediscover",
    "opmlDetail": "Exporta tus suscripciones como OPML desde otro lector e impórtalas en Radar para seguir descubriendo nuevos artículos de tus fuentes habituales.",
    "sharedDetail": "Crea un espacio, invita a otras personas y comparte páginas que merezcan una conversación. Construye una colección compartida junto a tu biblioteca personal.",
    "jevDetail": "Jev ayuda con decisiones concretas, como cuándo mostrar descubrimientos de Radar y cómo organizar categorías. Puedes activar esta ayuda por separado cuando la necesites.",
    "routerDetail": "Usa modelos en la nube para resúmenes, clasificación y guías de lectura. BYOK te permite gestionar tu conexión OpenRouter; Pro+ también ofrece IA en la nube sin clave propia."
  }
} satisfies Record<Language, FeatureCopy>;
